config/routes.rb
Rails.application.routes.draw do
  devise_for :users
<<<<<<< HEAD
  resources :students
  #get 'home/index'
  root 'home#index'
  get  'home/test'
=======
  
  resources :data
  #get 'home/index'
  root 'home#index'
  get 'home/page_b'
>>>>>>> 0ec91cea4d20bbb0ad7c1dc88e9df67dc2f021af

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/datum.rb
class Datum < ApplicationRecord
	belongs_to :user
end

app/models/student.rb
class Student < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
<<<<<<< HEAD
          
          has_many :students

=======

         has_many :datums
>>>>>>> 0ec91cea4d20bbb0ad7c1dc88e9df67dc2f021af
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  before_action :set_datum, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only:[:edit, :update, :destroy]

  # GET /data or /data.json
  def index
    @data = Datum.all
  end

  # GET /data/1 or /data/1.json
  def show
  end

  # GET /data/new
  def new
    #@datum = Datum.new
    @datum = current_user.datums.build
  end

  # GET /data/1/edit
  def edit
  end

  # POST /data or /data.json
  def create
    #@datum = Datum.new(datum_params)
    @datum = current_user.datums.build(datum_params)

    respond_to do |format|
      if @datum.save
        format.html { redirect_to datum_url(@datum), notice: "Datum was successfully created." }
        format.json { render :show, status: :created, location: @datum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data/1 or /data/1.json
  def update
    respond_to do |format|
      if @datum.update(datum_params)
        format.html { redirect_to datum_url(@datum), notice: "Datum was successfully updated." }
        format.json { render :show, status: :ok, location: @datum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data/1 or /data/1.json
  def destroy
    @datum.destroy!

    respond_to do |format|
      format.html { redirect_to data_url, notice: "Datum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @datum = correct_user.datums.find_by(id: params[:id])
    redirect_to datums_path, notice: "Cant find student" if @datum.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datum
      @datum = Datum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def datum_params
      params.require(:datum).permit(:first_name, :last_name, :phone, :email, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

<<<<<<< HEAD
  def test
  end

=======
  def page_b
  end
  
>>>>>>> 0ec91cea4d20bbb0ad7c1dc88e9df67dc2f021af
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  #before_action :correct_user, only:[:edit, :update, :destroy]


  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    #@student = Student.new
    @student = current_user.students.build
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    #@student = Student.new(student_params)
    @student = current_user.students.build(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy!

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @student = correct_user.students.find_by(id: params[:id])
    #If user tries to CRUD a student that doesnt belongs it will show the message
    redirect_to students_path,notice: "Action not allowed" if @student.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :last_name, :id, :email, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/data/_datum.html.erb
<div id="<%= dom_id datum %>">
  <p>
    <strong>First name:</strong>
    <%= datum.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= datum.last_name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= datum.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= datum.email %>
  </p>

</div>

app/views/data/_form.html.erb
<%= form_with(model: datum) do |form| %>
  <% if datum.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(datum.errors.count, "error") %> prohibited this datum from being saved:</h2>

      <ul>
        <% datum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

   <div>
    <%= form.label :user_id, style: "display: block", type: :hidden %>
    <%= form.number_field :user_id, id: :data_user_id, value:current_user.id , type: :hidden %>
  </div>



  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/data/edit.html.erb
<h1>Editing datum</h1>

<%= render "form", datum: @datum %>

<br>

<div>
  <%= link_to "Show this datum", @datum %> |
  <%= link_to "Back to data", data_path %>
</div>

app/views/data/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Data view</h1>


  <table class="table table-striped table table-hover">
  <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Phone</th>
      <th scope="col">Email</th>
      <th scope="col">User Id</th>
      <th scope="col">View student</th>
      
    </tr>
  </thead>
  <tbody>
    <% @data.each do |datum| %>
      <tr>
        
        <td><%= datum.first_name %></td>
        <td><%= datum.last_name %></td>
        <td><%= datum.phone %></td>
        <td><%= datum.email %></td>
        <td><%= datum.user_id %></td>
        <td><%= link_to "Show this datum", datum %></td>
        <td><%= link_to "Edit", datum %></td>
        <td><%= link_to "Destroy", datum, method: :delete, data:{confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
    
  </tbody>
</table>
</div>

<%= link_to "New datum", new_datum_path %>

app/views/data/new.html.erb
<h1>New datum</h1>

<%= render "form", datum: @datum %>

<br>

<div>
  <%= link_to "Back to data", data_path %>
</div>

app/views/data/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @datum %>

<div>
  <%= link_to "Edit this datum", edit_datum_path(@datum) %> |
  <%= link_to "Back to data", data_path %>

  <%= button_to "Destroy this datum", @datum, method: :delete %>
</div>


<div class="card text-center">
  <div class="card-header">
    Student card
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= student.name %> <%= student.last_name %></h5>
    <p class="card-text"> Student id: <%= student.id %></p>
    <%= link_to "Edit this student", edit_student_path(@student), class:"btn btn-secondary" %>
  </div>
  <div class="card-footer text-body-secondary">
    <%= student.email %>
  </div>
</div>

app/views/home/_header.html.erb
<<<<<<< HEAD
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
          <%= link_to 'Test Page', home_test_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Students', students_path, class: "nav-link" %>
        </li>


      

        <% if user_signed_in?%>

        
          <li class="nav-item">
            <%= link_to 'Sing Out', destroy_user_session_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Edit User', edit_user_registration_path, class: "nav-link" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to 'Sing Up', new_user_registration_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Sing In', new_user_session_path, class: "nav-link" %>
          </li>

        <% end %>




        <!--<li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Edit Students
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Create</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li> --> 
          </ul>
        </li>

        

      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
=======
<!--<svg width="300" height="130" xmlns="http://www.w3.org/2000/svg">
  <rect width="200" height="100" x="10" y="10" rx="20" ry="20" fill="blue" />
</svg>--> 

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Rails Test',root_path,class:"navbar-brand" %> 
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Page B', home_page_b_path, class: "nav-link" %>

        </li>

        <li class="nav-item">
          <%= link_to 'Names', data_path, class: "nav-link" %>

        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Edit profile', edit_user_registration_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, class: "nav-link" %>

          </li>

        <% else %>

          <li class="nav-item">
            <%= link_to 'Sing Up', new_user_registration_path , class: "nav-link" %>

          </li>

        

          <li class="nav-item">
            <%= link_to 'Sing In', new_user_session_path, class: "nav-link" %>

          </li>
        <%end%>

        <li class="nav-item">
          <a class="nav-link" href="https://www.utrgv.edu/">Link</a>
        </li>

    
        </li>


        
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
>>>>>>> 0ec91cea4d20bbb0ad7c1dc88e9df67dc2f021af
</nav>

app/views/home/index.html.erb
<h1>Hello World!</h1>
<<<<<<< HEAD
<p><b>Ruby on Rails</b> exercise for 1380 Spring 2024</p>
=======
<p>First Test</p>
>>>>>>> 0ec91cea4d20bbb0ad7c1dc88e9df67dc2f021af

app/views/home/page_b.html.erb
<h1> Page test b <h1>

app/views/home/test.html.erb
<h1>This is the test page</h1>

app/views/layouts/_alerts.html.erb
<<<<<<< HEAD
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
=======
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
>>>>>>> 0ec91cea4d20bbb0ad7c1dc88e9df67dc2f021af
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<<<<<<< HEAD
    <title>1380 Spring</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <div class = "container"> 
  <body>
      <%= render 'home/header' %>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
     

      <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
=======
    <title>Test Rails</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <div class = "container">
  <body>
     <%= render 'home/header' %>
     <% if notice %>
        <%= render 'layouts/alerts' %>
     <% end %>
     

     <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
  <div/>
>>>>>>> 0ec91cea4d20bbb0ad7c1dc88e9df67dc2f021af
</html>



<<<<<<< HEAD












=======
>>>>>>> 0ec91cea4d20bbb0ad7c1dc88e9df67dc2f021af

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :id, style: "display: block" %>
    <%= form.text_field :id %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    
    <%= form.number_field :user_id, id: :data_user_id, value:current_user.id, type: :hidden %>
  </div>

  
 

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  ><p>
    <strong>Name:</strong>
    <%= student.name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= student.last_name %>
  </p>

  <p>
    <strong>Id:</strong>
    <%= student.id %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= student.email %>
  </p>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>


<!-- This following code is the scaffold for the db rendering -->
<!-- <table class="table"> 

  <% @students.each do |student| %>
    <%= render student %>
    <p>
      <%= link_to "Show this student", student %>
    </p>
  <% end %>
</table>-->



<table class="table table-striped table table-hover">
  <thead>
    <tr>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Student id</th>
      <th scope="col">Email</th>
      <th scope="col">View student</th>
      <th scope="col">Owner</th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <% if student.user == current_user %>
        <td><%= student.name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.id %></td>
        <td><%= student.email %></td>
        
        <td><%= link_to "Show", student, class:"btn btn-outline-secondary" %></td>
        <td><%= student.user_id %></td>
        <td><%= link_to "Edit", student %></td>
        <td><%= link_to "Destroy", student, method: :delete, data:{confirm: 'Are you sure?'} %></td>
        <%end%>
      </tr>
    <% end %>
    
  </tbody>
</table>

<%= link_to "New student", new_student_path, class:"btn btn-secondary"  %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>



<div class="card text-center">
  <div class="card-header">
    Student card
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @student.name %> <%= @student.last_name %></h5>
    <p class="card-text"> Student id: <%= @student.id %></p>
    <p class="card-text"> Student email: <%= @student.email %></p>

    <%= link_to "Edit this student", edit_student_path(@student), class:"btn btn-secondary" %>
  </div>
  <div class="card-footer text-body-secondary">
    
  </div>
</div>

<div>

  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>